/* GENERATED BY scripts/optimise-images.mjs — DO NOT EDIT BY HAND.
 *
 * The responsive variants that exist on disk under /images/, keyed by the
 * ORIGINAL filename, which is the name src/config/site.ts still uses. <Img>
 * reads this to build srcset and to emit width/height for CLS (spec §14).
 *
 * `w`/`h`  intrinsic size of the top step. Aspect ratio only — the CSS
 *          decides the rendered box everywhere in this system.
 * `webp`  widths available as `NAME-<w>.webp`.
 * `jpeg`  widths available as `NAME-<w>.jpg`. The top width is NOT listed:
 *          it is the file named after the original, e.g. `img-00.jpg`, so a
 *          repo that never adopts <Img> still resolves every existing src.
 *
 * A filename absent from this map is not an error. <Img> falls back to a
 * plain <img src="/images/NAME"> — which is exactly what the site did before
 * this pipeline existed, so an unprocessed asset degrades, never breaks.
 */

export interface ImageVariants {
  /** Intrinsic width of the largest emitted step. */
  w: number;
  /** Intrinsic height of the largest emitted step. */
  h: number;
  /** Widths emitted as `NAME-<w>.webp`. */
  webp: number[];
  /** Widths emitted as `NAME-<w>.jpg`, excluding the top step. */
  jpeg: number[];
}

export const IMAGE_MANIFEST: Record<string, ImageVariants> = {
  "hero.jpg": { w: 1208, h: 1080, webp: [480, 960, 1208], jpeg: [480] },
  "img-00.jpg": { w: 1208, h: 1080, webp: [480, 960, 1208], jpeg: [480] },
  "img-01.jpg": { w: 810, h: 1080, webp: [480, 810], jpeg: [480] },
  "img-02.jpg": { w: 1600, h: 899, webp: [480, 960, 1600], jpeg: [480] },
  "img-03.jpg": { w: 810, h: 1080, webp: [480, 810], jpeg: [480] },
  "img-04.jpg": { w: 810, h: 1080, webp: [480, 810], jpeg: [480] },
  "img-05.jpg": { w: 608, h: 1080, webp: [480, 608], jpeg: [480] },
  "img-06.jpg": { w: 1024, h: 678, webp: [480, 960, 1024], jpeg: [480] },
};
